variables:
  PLUGIN_NAME: 'referencesForChapters'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_4_0
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/omp/cypress_tests.yml'

omp_integration_tests:
  rules:
    - when: never