variables:
  PLUGIN_NAME: 'referencesForChapters'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/omp/cypress_tests.yml'